name: Compile Examples with Free Pascal

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  compile-fpc-examples:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Install Free Pascal
      run: |
        sudo apt-get -qq update
        sudo apt-get -yq install fpc
       
    - name: Compile simple example
      run: |
        cd examples/simple
        fpc -Sd -Fu../../src/main HelloWorld.dpr

    - name: Run simple example
      run: examples/simple/HelloWorld

    - name: Compile named logger example
      run: |
        cd examples/named
        fpc -Sd -Fu../../src/main HelloWorld.dpr

    - name: Run example
      run: examples/named/HelloWorld
      
    
